"""Runtime metadata for Agent tools.

Provider schemas intentionally remain unchanged; this descriptor is consumed by
policy, approval and observability layers so side effects are not inferred from
tool names scattered through the loop.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ToolDescriptor:
    name: str
    tool_class: type
    category: str
    read_only: bool
    mutates: bool
    approval_required: bool
    approval_severity: str
    supports_proposal: bool
    timeout_class: str
    result_schema: dict[str, Any]
    legacy_write: bool = False


_PROPOSAL_TOOLS = frozenset({
    "rewrite_star", "translate", "rewrite_resume", "generate_module", "modify_module",
})
_LEGACY_WRITES = frozenset({"save_memory", "jd_match", "interview_coach"})
_LONG_TOOLS = frozenset({"web_search", "search_jobs_live", "spawn"})


def describe_tool(tool_class: type) -> ToolDescriptor:
    name = str(getattr(tool_class, "name", ""))
    proposal = name in _PROPOSAL_TOOLS
    legacy = name in _LEGACY_WRITES
    mutates = proposal or legacy
    args_model = getattr(tool_class, "args_model", None)
    result_schema = {"type": "string"}
    if args_model is not None:
        # Result schema is deliberately transport-neutral; provider function
        # schemas are still generated by Tool.to_openai_schema().
        result_schema = {"type": "string"}
    return ToolDescriptor(
        name=name,
        tool_class=tool_class,
        category=str(getattr(tool_class, "category", "unknown") or "unknown"),
        read_only=not mutates,
        mutates=mutates,
        approval_required=bool(getattr(tool_class, "requires_approval", False)),
        approval_severity=str(getattr(tool_class, "approval_severity", "warning") or "warning"),
        supports_proposal=proposal,
        timeout_class="long" if name in _LONG_TOOLS else "standard",
        result_schema=result_schema,
        legacy_write=legacy,
    )


def build_tool_descriptors(tool_classes: list[type]) -> dict[str, ToolDescriptor]:
    descriptors: dict[str, ToolDescriptor] = {}
    for tool_class in tool_classes:
        descriptor = describe_tool(tool_class)
        if not descriptor.name:
            raise ValueError("tool descriptor requires a non-empty name")
        if descriptor.name in descriptors:
            raise ValueError(f"duplicate tool name: {descriptor.name}")
        descriptors[descriptor.name] = descriptor
    return descriptors
