/**
 * iconsMap — @phosphor-icons/react → lucide-react 全量映射表（M1 图标迁移）。
 *
 * 全站 47 个文件从 phosphor 迁移到 lucide-react 的唯一数据源：
 * - 迁移脚本按此表改 import
 * - icons.test.ts 遍历此表断言 lucide 均导出（防遗漏门禁）
 *
 * 命名约定：
 * - weight="regular" → 删除属性（lucide 默认 strokeWidth=2）
 * - weight="bold"    → strokeWidth={2.25}
 * - weight="fill"|"duotone" → 删除 + fill="currentColor"（约 15 处手工）
 * - type Icon → type LucideIcon
 */

export const PHOSPHOR_TO_LUCIDE: Record<string, string> = {
  Archive: "Archive",
  ArrowClockwise: "RotateCw",
  ArrowCounterClockwise: "RotateCcw",
  ArrowLeft: "ArrowLeft",
  ArrowRight: "ArrowRight",
  ArrowUUpLeft: "CornerUpLeft",
  ArrowsClockwise: "RefreshCw",
  ArrowsInSimple: "Minimize2",
  ArrowsOutSimple: "Maximize2",
  Article: "FileText",
  Bell: "Bell",
  BookmarkSimple: "Bookmark",
  Books: "Library",
  Briefcase: "Briefcase",
  Building: "Building2",
  CalendarBlank: "CalendarDays",
  CaretDown: "ChevronDown",
  CaretLeft: "ChevronLeft",
  CaretRight: "ChevronRight",
  CaretUp: "ChevronUp",
  Certificate: "Award",
  ChartBar: "ChartColumn",
  ChatCircle: "MessageCircle",
  ChatCircleDots: "MessagesSquare",
  ChatCircleText: "MessageSquareText",
  ChatTeardropText: "MessageSquareText",
  ChatsCircle: "MessagesSquare",
  Check: "Check",
  CheckCircle: "CircleCheck",
  Checks: "CheckCheck",
  CircleHalf: "Contrast",
  ClipboardText: "ClipboardList",
  ClockCounterClockwise: "History",
  Code: "Code",
  Compass: "Compass",
  Copy: "Copy",
  Crosshair: "Crosshair",
  Database: "Database",
  DotsSixVertical: "GripVertical",
  DotsThree: "Ellipsis",
  DotsThreeCircle: "BrainCircuit",
  EnvelopeSimple: "Mail",
  Export: "Download",
  Eye: "Eye",
  EyeSlash: "EyeOff",
  Eyeglasses: "Glasses",
  FilePdf: "FileDown",
  FilePlus: "FilePlus",
  FileText: "FileText",
  FirstAidKit: "BriefcaseMedical",
  Flag: "Flag",
  FloppyDisk: "Save",
  FolderOpen: "FolderOpen",
  Gauge: "Gauge",
  Gear: "Settings",
  Ghost: "Ghost",
  GitBranch: "GitBranch",
  GitDiff: "GitCompare",
  Globe: "Globe",
  GlobeSimple: "Globe",
  GraduationCap: "GraduationCap",
  GridFour: "LayoutGrid",
  HandCoins: "HandCoins",
  Hash: "Hash",
  Key: "KeyRound",
  Lightning: "Zap",
  LinkSimple: "Link",
  ListBullets: "List",
  ListChecks: "ListChecks",
  ListNumbers: "ListOrdered",
  LockSimple: "Lock",
  MagnifyingGlass: "Search",
  MapPin: "MapPin",
  MapTrifold: "Map",
  Microphone: "Mic",
  Minus: "Minus",
  Money: "Banknote",
  Monitor: "Monitor",
  Moon: "Moon",
  NotePencil: "SquarePen",
  PaintBrush: "Paintbrush",
  Palette: "Palette",
  PaperPlaneRight: "SendHorizontal",
  PaperPlaneTilt: "Send",
  Paperclip: "Paperclip",
  PencilSimple: "Pencil",
  Plus: "Plus",
  PlusSquare: "SquarePlus",
  Printer: "Printer",
  Prohibit: "Ban",
  Question: "CircleHelp",
  ReadCvLogo: "FileUser",
  Scales: "Scale",
  SealCheck: "BadgeCheck",
  ShareNetwork: "Share2",
  Shield: "Shield",
  ShieldCheck: "ShieldCheck",
  ShieldWarning: "ShieldAlert",
  SignIn: "LogIn",
  SignOut: "LogOut",
  Sparkle: "Sparkles",
  Spinner: "LoaderCircle",
  SpinnerGap: "Loader",
  Stop: "Square",
  SuitcaseSimple: "Luggage",
  Sun: "Sun",
  Swap: "ArrowRightLeft",
  Table: "Table",
  Target: "Target",
  TextAa: "Type",
  TextAlignJustify: "AlignJustify",
  TextB: "Bold",
  TextHOne: "Heading1",
  TextHTwo: "Heading2",
  TextItalic: "Italic",
  ThumbsDown: "ThumbsDown",
  ThumbsUp: "ThumbsUp",
  Translate: "Languages",
  Trash: "Trash2",
  TrashSimple: "Trash",
  TrendUp: "TrendingUp",
  Trophy: "Trophy",
  Upload: "Upload",
  UploadSimple: "Upload",
  User: "User",
  UserCircle: "CircleUser",
  UserMinus: "UserMinus",
  Users: "Users",
  UsersThree: "Users",
  Warning: "TriangleAlert",
  WarningCircle: "CircleAlert",
  Wrench: "Wrench",
  X: "X",
};
